In [1]:
import tensorflow as tf
from tensorflow import keras

import pandas as pd
import numpy as np

# Linear - simplest classification

### Classify if dot is red or blue

<img src="https://github.com/KeithGalli/neural-nets/blob/master/examples/linear/figure.png?raw=true" />

In [ ]:
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/linear/data/train.csv
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/linear/data/test.csv
!mkdir -p data
!mv train.csv data/train.csv
!mv test.csv data/test.csv

--2023-05-19 13:10:44--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/linear/data/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 165238 (161K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>] 161.37K  --.-KB/s    in 0.01s   

2023-05-19 13:10:44 (10.6 MB/s) - ‘train.csv’ saved [165238/165238]

--2023-05-19 13:10:44--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/linear/data/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 

In [ ]:
train_df = pd.read_csv('./data/train.csv')
np.random.shuffle(train_df.values)

train_df.head()

x         y  color
0  1.718725  0.819522    1.0
1  4.586811  5.462708    0.0
2  4.171289  3.257468    1.0
3  4.639014  5.215073    0.0
4  4.482917  3.496453    1.0

#### Netowk definition and its layers

In [ ]:
"""

Network look :  2 neurons -> 4 neuron -> 2 neurons
       o
  X -- o -- o
  Y -- o -- o
       o

"""

# Sequential allows us to list layers we want to have in our network
model = keras.Sequential(
    [
        keras.layers.Dense(units=4, input_shape=(2,), activation='relu'), # First hidden layer has 4 units, input X,Y so dim = 2, RELU activation function -> default one
        keras.layers.Dense(2, activation='sigmoid')
    ]
)

model.compile(
    optimizer='adam',
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

#### Data Prep and Training model

In [ ]:
# model.fit([x], [y], [batch_size])

# Pandas DF -> Numpy
x = np.column_stack((train_df.x.values, train_df.y.values))

model.fit(x, train_df.color.values, batch_size=4, epochs=5)


Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1000/1000 [==============================] - 3s 2ms/step - loss: 0.6853 - accuracy: 0.6990
Epoch 2/5
1000/1000 [==============================] - 2s 2ms/step - loss: 0.2365 - accuracy: 0.9935
Epoch 3/5
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0963 - accuracy: 1.0000
Epoch 4/5
1000/1000 [==============================] - 3s 3ms/step - loss: 0.0447 - accuracy: 1.0000
Epoch 5/5
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0228 - accuracy: 1.0000


#### Test Data

In [ ]:
test_df = pd.read_csv('./data/test.csv')
test_x = np.column_stack((test_df.x.values, test_df.y.values))

model.evaluate(test_x, test_df.color.values)

22/32 [===================>..........] - ETA: 0s - loss: 0.0135 - accuracy: 1.0000

/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


32/32 [==============================] - 0s 3ms/step - loss: 0.0159 - accuracy: 1.0000


[0.01586407981812954, 1.0]

# Quadratic

<img src="https://github.com/KeithGalli/neural-nets/blob/master/examples/quadratic/figure.png?raw=true" />

In [ ]:
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/quadratic/data/train.csv
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/quadratic/data/test.csv
!mkdir -p data
!mv train.csv data/train.csv
!mv test.csv data/test.csv

--2023-05-19 13:46:10--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/quadratic/data/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 167164 (163K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>] 163.25K  --.-KB/s    in 0.02s   

2023-05-19 13:46:10 (9.18 MB/s) - ‘train.csv’ saved [167164/167164]

--2023-05-19 13:46:10--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/quadratic/data/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Le

In [ ]:
# Almost the same code 

# Reading training data
train_df = pd.read_csv('./data/train.csv')
np.random.shuffle(train_df.values)

print(train_df.head())

# Here without adding a new layer we would get accuracy about 70% but we want more so we add relu layerand increase the neuron numbers per layer
model = keras.Sequential([
	keras.layers.Dense(32, input_shape=(2,), activation='relu'),
	keras.layers.Dense(32, activation='relu'), # additional layer -> drop out at 20% doing do better so relu
	keras.layers.Dense(2, activation='sigmoid')])

model.compile(optimizer='adam', 
	          loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
	          metrics=['accuracy'])

x = np.column_stack((train_df.x.values, train_df.y.values))

model.fit(x, train_df.color.values, batch_size=4, epochs=10)

test_df = pd.read_csv('./data/test.csv')
test_x = np.column_stack((test_df.x.values, test_df.y.values))


          x          y  color
0 -2.076833   6.105529    0.0
1  4.986938  26.298164    0.0
2 -2.199684   6.775975    0.0
3  4.606364  19.309756    1.0
4  0.238857  -1.239804    1.0
Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1000/1000 [==============================] - 2s 2ms/step - loss: 0.5207 - accuracy: 0.7412
Epoch 2/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.2957 - accuracy: 0.8903
Epoch 3/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.2036 - accuracy: 0.9270
Epoch 4/10
1000/1000 [==============================] - 3s 3ms/step - loss: 0.1317 - accuracy: 0.9635
Epoch 5/10
1000/1000 [==============================] - 3s 3ms/step - loss: 0.1145 - accuracy: 0.9645
Epoch 6/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0726 - accuracy: 0.9827
Epoch 7/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0815 - accuracy: 0.9740
Epoch 8/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0544 - accuracy: 0.9858
Epoch 9/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0636 - accuracy: 0.9845
Epoch 10/10
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0372 - accurac

In [ ]:
model.evaluate(test_x, test_df.color.values)

32/32 [==============================] - 0s 2ms/step - loss: 0.0189 - accuracy: 1.0000


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


[0.01894599385559559, 1.0]

# Clusters

<img src="https://github.com/KeithGalli/neural-nets/blob/master/examples/clusters/figure.png?raw=true" alt="chart" />

In [ ]:
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters/data/train.csv
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters/data/test.csv
!mkdir -p data
!mv train.csv data/train.csv
!mv test.csv data/test.csv

--2023-05-19 13:47:59--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters/data/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 263244 (257K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>] 257.07K  --.-KB/s    in 0.02s   

2023-05-19 13:47:59 (15.1 MB/s) - ‘train.csv’ saved [263244/263244]

--2023-05-19 13:47:59--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters/data/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Leng

#### READING DATA AND SLIGHT MODIFICATION -> 6 COLORS STRINGS TO NUMERICAL VALUE

In [ ]:
train_df = pd.read_csv('./data/train.csv')

# WE KNOW THERE ARE ONLY 6 COLORS SO DICT IS IN PLACE
color_dict = {'red': 0, 'blue': 1, 'green': 2, 'teal': 3, 'orange': 4, 'purple': 5}

train_df['color'] = train_df.color.apply(lambda x: color_dict[x])
np.random.shuffle(train_df.values)

In [ ]:
print(train_df.head())
print(train_df.color.unique())

          x         y  color
0  0.129270  1.979720      0
1 -0.380831  1.693519      0
2  0.718693  1.791793      0
3  0.722922  0.620655      0
4 -0.432689  0.541550      0
[0 1 2 3 4 5]


In [ ]:
# 32 NEURONS -> 32 NEURONS -> 6 NEURONS ( 6 SINCE 6 COLORS - NO LONGER 2 COLORS )

model = keras.Sequential([
	keras.layers.Dense(32, input_shape=(2,), activation='relu'),
	keras.layers.Dense(32, activation='relu'),
	keras.layers.Dense(6, activation='sigmoid')])

model.compile(
    optimizer='adam', 
	  loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
	  metrics=['accuracy']
)

In [ ]:
x = np.column_stack((train_df.x.values, train_df.y.values))

model.fit(x, train_df.color.values, batch_size=4, epochs=10)

test_df = pd.read_csv('./data/test.csv')
test_x = np.column_stack((test_df.x.values, test_df.y.values))

Epoch 1/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.5421 - accuracy: 0.8083
Epoch 2/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.1645 - accuracy: 0.9503
Epoch 3/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.1202 - accuracy: 0.9590
Epoch 4/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.1014 - accuracy: 0.9652
Epoch 5/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0896 - accuracy: 0.9677
Epoch 6/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.0809 - accuracy: 0.9702
Epoch 7/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0787 - accuracy: 0.9685
Epoch 8/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0755 - accuracy: 0.9688
Epoch 9/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0723 - accuracy: 0.9723
Epoch 10/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.066

#### EVALUATION

In [ ]:
test_df['color'] = test_df.color.apply(lambda x: color_dict[x]) # SAME COLOR TRANSFORMATION AS FOR TRAIN DATA
model.evaluate(test_x, test_df.color.values)

22/38 [================>.............] - ETA: 0s - loss: 0.0667 - accuracy: 0.9716

/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


38/38 [==============================] - 0s 3ms/step - loss: 0.0670 - accuracy: 0.9733


[0.06704011559486389, 0.9733333587646484]

#### PREDICTION

In [ ]:
# PREDICTION FOR A SINGLE POINT A(0,3)
np.round( model.predict(np.array([[0,3]])) )

1/1 [==============================] - 0s 102ms/step


array([[0., 0., 0., 0., 0., 1.]], dtype=float32)

# 2 CATEGORIES PREDICTION - BOTH COLOR AND MARKER

<img src="https://github.com/KeithGalli/neural-nets/blob/master/examples/clusters_two_categories/figure.png?raw=true" />

#### Data Format: [ x ] [ y ] [ color ] [ marker sign ]

In [2]:
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters_two_categories/data/train.csv
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/clusters_two_categories/data/test.csv
!mkdir -p data
!mv train.csv data/train.csv
!mv test.csv data/test.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'mv' is not recognized as an internal or external command,
operable program or batch file.
'mv' is not recognized as an internal or external command,
operable program or batch file.


#### Prevoisly
Input data 
```
3 # just color from 1-5
```

#### Now:

first numbers in vector represent color and last 2 one of 2 markers
```
[0 0 0 0 0 1 0 0 1]
 --- color --- 
               --- <- marker 
```


In [4]:
train_df = pd.read_csv('./data/train.csv')
test_df = pd.read_csv('./data/test.csv')

In [5]:
# pandas.get_dummies() does exactly that for us
# one-hot encoding refers to encoding where 1 is the only true value np [ red green blue ] -> [ 0 1 0 ] means its green

one_hot_color = pd.get_dummies(train_df['color']).values
one_hot_marker = pd.get_dummies(train_df['marker']).values

# to color [0 0 0 0 1 0 0] add marker [ 0 1 ] 
labels = np.concatenate((one_hot_color, one_hot_marker), axis=1)
print(labels[0])

print(train_df.head())

[0 0 0 0 1 0 0 0 1]
          x         y color marker
0 -0.765775  1.006452   red      ^
1  0.229016  0.094320   red      ^
2  0.189987  1.589141   red      ^
3  0.580085  0.520488   red      ^
4  0.292287  0.317852   red      ^


In [6]:
# Create the model
model = keras.Sequential([
    keras.layers.Dense(64, input_shape=(2,), activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(labels.shape[1], activation='sigmoid')
])

# Compile the model
# BinaryCross entropy considers each value in vector [ 0 0 0 0 0 1 1 0 ] independently of another so that allows us to have 2 categories this way
model.compile(optimizer='adam',
              loss=keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])


In [7]:
x_train = train_df[['x', 'y']].values
# x_train =  np.column_stack((train_df.x.values, train_df.y.values))

# Shuffle the input data and labels together
# Here we must ensure that random shuffle is at the same rate both for x and labels with same seed
np.random.RandomState(seed=42).shuffle(x_train)
np.random.RandomState(seed=42).shuffle(labels)

# Train the model
model.fit(x_train, labels, batch_size=4, epochs=10)

#            labels instead of train_df.color.values

Epoch 1/10


C:\Users\Andrzej\AppData\Roaming\Python\Python39\site-packages\keras\backend.py:5703: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Sigmoid activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1500/1500 [==============================] - 2s 718us/step - loss: 0.1961 - accuracy: 0.2653
Epoch 2/10
1500/1500 [==============================] - 1s 749us/step - loss: 0.0670 - accuracy: 0.3532
Epoch 3/10
1500/1500 [==============================] - 1s 763us/step - loss: 0.0468 - accuracy: 0.3093
Epoch 4/10
1500/1500 [==============================] - 1s 748us/step - loss: 0.0372 - accuracy: 0.3070
Epoch 5/10
1500/1500 [==============================] - 1s 785us/step - loss: 0.0327 - accuracy: 0.3087
Epoch 6/10
1500/1500 [==============================] - 1s 722us/step - loss: 0.0305 - accuracy: 0.3017
Epoch 7/10
1500/1500 [==============================] - 1s 747us/step - loss: 0.0282 - accuracy: 0.2942
Epoch 8/10
1500/1500 [==============================] - 1s 814us/step - loss: 0.0257 - accuracy: 0.2812
Epoch 9/10
1500/1500 [==============================] - 1s 830us/step - loss: 0.0251 - accuracy: 0.2688
Epoch 10/10
1500/1500 [==============================] - 1s 821us/step - lo

In [8]:
# Prepare the test data
x_test = test_df[['x', 'y']].values

# Perform one-hot encoding for test data
test_one_hot_color = pd.get_dummies(test_df['color']).values
test_one_hot_marker = pd.get_dummies(test_df['marker']).values
test_labels = np.concatenate((test_one_hot_color, test_one_hot_marker), axis=1)

# Evaluate the model
print("Evaluation")
model.evaluate(x_test, test_labels)

Evaluation
38/38 [==============================] - 0s 673us/step - loss: 0.0202 - accuracy: 0.2825


C:\Users\Andrzej\AppData\Roaming\Python\Python39\site-packages\keras\backend.py:5703: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Sigmoid activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


[0.020175468176603317, 0.2824999988079071]

In [76]:
print("Prediction", np.round(model.predict(np.array([[0,3], [0,1], [-2, 1]]))))

1/1 [==============================] - 0s 71ms/step
Prediction [[0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]]


# COMPLEX DATA

<img src="https://github.com/KeithGalli/neural-nets/blob/master/examples/complex/figure.png?raw=true" />

In [79]:
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/complex/data/train.csv
!wget https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/complex/data/test.csv
!mkdir -p data
!mv train.csv data/train.csv
!mv test.csv data/test.csv

--2023-05-19 15:43:25--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/complex/data/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 844057 (824K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>] 824.27K  --.-KB/s    in 0.03s   

2023-05-19 15:43:26 (30.6 MB/s) - ‘train.csv’ saved [844057/844057]

--2023-05-19 15:43:26--  https://raw.githubusercontent.com/KeithGalli/neural-nets/master/examples/complex/data/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length

In [80]:
train_df = pd.read_csv('./data/train.csv')
np.random.shuffle(train_df.values)

print(train_df.head())

          x         y  color
0 -0.608973 -2.885010    0.0
1 -0.732411  1.520680    1.0
2  3.521092  2.310161    1.0
3 -0.265030  1.699833    1.0
4  1.962163 -3.768290    0.0


In [81]:
model = keras.Sequential([
	keras.layers.Dense(256, input_shape=(2,), activation='relu'),
	keras.layers.Dropout(0.4),
	keras.layers.Dense(128, activation='relu'),
	keras.layers.Dropout(0.4),
	keras.layers.Dense(128, activation='relu'),
	keras.layers.Dense(2, activation='sigmoid')
 ])

model.compile(optimizer='adam', 
	          loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
	          metrics=['accuracy'])


In [82]:
x = np.column_stack((train_df.x.values, train_df.y.values))

model.fit(x, train_df.color.values, batch_size=32, epochs=20)

Epoch 1/20


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


625/625 [==============================] - 4s 5ms/step - loss: 0.6296 - accuracy: 0.6134
Epoch 2/20
625/625 [==============================] - 2s 3ms/step - loss: 0.5965 - accuracy: 0.6690
Epoch 3/20
625/625 [==============================] - 2s 3ms/step - loss: 0.5550 - accuracy: 0.7192
Epoch 4/20
625/625 [==============================] - 2s 3ms/step - loss: 0.5253 - accuracy: 0.7422
Epoch 5/20
625/625 [==============================] - 2s 3ms/step - loss: 0.5053 - accuracy: 0.7542
Epoch 6/20
625/625 [==============================] - 2s 3ms/step - loss: 0.4822 - accuracy: 0.7662
Epoch 7/20
625/625 [==============================] - 2s 3ms/step - loss: 0.4686 - accuracy: 0.7765
Epoch 8/20
625/625 [==============================] - 2s 4ms/step - loss: 0.4571 - accuracy: 0.7835
Epoch 9/20
625/625 [==============================] - 2s 3ms/step - loss: 0.4389 - accuracy: 0.7936
Epoch 10/20
625/625 [==============================] - 2s 3ms/step - loss: 0.4307 - accuracy: 0.7966
Epoch 11/2

In [83]:
test_df = pd.read_csv('./data/test.csv')
test_x = np.column_stack((test_df.x.values, test_df.y.values))

print("EVALUATION")
model.evaluate(test_x, test_df.color.values)

EVALUATION
 28/157 [====>.........................] - ETA: 0s - loss: 0.2748 - accuracy: 0.8728 

/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


157/157 [==============================] - 0s 2ms/step - loss: 0.2954 - accuracy: 0.8614


[0.2953557074069977, 0.8614000082015991]

In [84]:
print("Prediction", np.round(model.predict(np.array([[0,3], [0,1], [-2, 1]]))))

1/1 [==============================] - 0s 78ms/step
Prediction [[1. 1.]
 [1. 1.]
 [0. 1.]]
